### ISSUE TITLE
move-toでゴールに到達していなくてもsuccessが返ってくる

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_common#155]
_This post was originally posted at http://sourceforge.net/p/jsk-ros-pkg/tickets/160_

jsk_2013_04_pr2_610デモ(`rospack find jsk_2013_04_pr2_610`/euslisp/setup.l) において、
move-toでPR2を動かすときにeng8-610の入口付近から_laundry-spot_へ動かそうとすると、
目標位置に到達していないにも関わらずSuccessと出てmove-toが完了してしまいます。
一方、別の位置（例えば_broom-spot_）へ一度move-toしてから_laundry-spot_へ動かすと正常に動きます。

サンプルのコマンドは

```
(send *ri* :move-to (make-coords :pos #f(3376.358 1309.163 -0.854) :rpy #f(1.544 0.004 0.002)) :frame-id "/eng8/6f/610")

```

になります．

```
rostopic echo /move_base/result
```

をすると

```

---
header: 
  seq: 97
  stamp: 
    secs: 1369911817
    nsecs: 426065503
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1369911817
      nsecs: 325378450
    id: #i(1369911817 312803158)
  status: 3
  text: Goal reached.
result: 

---
```

となるのでmove_baseがおかしいかもしれません。
